apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  template:
    spec:
      containers:
        - name: grafana
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
              subPath: grafana
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
