apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  template:
    spec:
      containers:
        - name: influxdb
          volumeMounts:
            - name: data
              mountPath: /root/.influxdbv2
              subPath: influxdb
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
