mqtt:
  broker: "mosquitto"
  port: 1883
  client_id: "garden-controller"
  water_topic: "{{.Garden}}/command/water"
  stop_topic: "{{.Garden}}/command/stop"
  stop_all_topic: "{{.Garden}}/command/stop_all"
  light_topic: "{{.Garden}}/command/light"
controller:
  topic_prefix: "garden"
  num_zones: 3
  moisture_strategy: increasing
  moisture_value: 0
  moisture_interval: 30s
  publish_water_event: true
  publish_health: true
  health_interval: 1m
