comment:
  layout: "header, diff, flags, components"

component_management:
  individual_components:
    - component_id: garden-app
      name: garden-app
      paths:
        - garden-app

ignore:
  - garden-controller
  - deploy
  - iOS_App
  - docs
  - garden-app/pkg/weather/netatmo # ignore because it is basically untestable
  - "*_test.go"
