version: "3"

tasks:
  integration-test:
    aliases: ["it"]
    desc: Startup docker resources and run integration tests. Cleanup when done.
    dir: ./garden-app
    cmds:
      - docker compose -f ../deploy/docker-compose.yml --profile test up -d
      - defer: docker volume rm deploy_influxdb
      - defer: docker compose -f ../deploy/docker-compose.yml --profile test down
      - sleep 15
      - go test -race -covermode=atomic -coverprofile=integration_coverage.out -coverpkg=./... ./integration_tests

  unit-test:
    aliases: ["ut"]
    desc: Run unit tests for Go app
    dir: ./garden-app
    cmds:
      - go test -short -race -covermode=atomic -coverprofile=coverage.out -coverpkg=./... {{.CLI_ARGS}} ./...

  lint:
    desc: Run linting for Go app
    dir: ./garden-app
    cmds:
      - golangci-lint run

  gofumpt:
    desc: Run gofumpt to format Go app
    dir: ./garden-app
    cmd: gofumpt -w .

  up:
    desc: Start docker containers for run-local (optional args for -d)
    dir: ./deploy
    cmds:
      - docker compose --profile run-local up {{.CLI_ARGS}}

  down:
    desc: Remove docker containers for run-local
    dir: ./deploy
    cmds:
      - docker compose --profile run-local down

  run:
    desc: Run Go app
    dir: ./garden-app
    cmds:
      - go run main.go {{.CLI_ARGS}}

  run-server:
    desc: Run backend Go app server
    aliases: [rs]
    dir: ./garden-app
    cmds:
      - go run main.go serve --config config.yaml

  run-dev:
    desc: Run backend Go app server and read UI templates from local FS
    aliases: [dev]
    dir: ./garden-app
    cmds:
      - DEV_TEMPLATE=server/templates/* go run main.go serve --config config.yaml

  run-controller:
    desc: Run mock controller
    aliases: [rc]
    dir: ./garden-app
    cmds:
      - go run main.go controller --config config.yaml --enable-ui=false

  run-docker:
    desc: Run backend in Docker container
    aliases: [rd]
    dir: ./garden-app
    cmds:
      - |
        docker run --rm --network host \
        -v ./gardens.yaml:/gardens.yaml \
        -v ./config.yaml:/config.yaml \
        ghcr.io/calvinmclean/garden-app:{{.CLI_ARGS | default "latest"}} \
        serve --config /config.yaml

  generate-mocks:
    desc: Use mockery to generate mocks from Go interfaces
    dir: ./garden-app/pkg
    cmds:
      - mockery --all --inpackage

  docker-build:
    desc: Build docker container
    dir: ./garden-app
    cmds:
      - docker build --target {{.TARGET}} -t ghcr.io/calvinmclean/garden-app:{{.TAG}} .
    vars:
      TAG: '{{default "latest" .TAG}}'
      TARGET: '{{default "production" .TARGET}}'

  docker-build-demo:
    cmds:
      - task: docker-build
        vars:
          TAG: "demo"
          TARGET: "demo"

  docker-push-demo:
    cmds:
      - task: docker-push
        vars:
          TAG: "demo"
          TARGET: "demo"

  docker-push:
    desc: Build and push docker container
    dir: ./garden-app
    cmds:
      - task: docker-build
      - docker push ghcr.io/calvinmclean/garden-app:{{.TAG}}
    vars:
      TAG: '{{default "latest" .TAG}}'
      TARGET: '{{default "production" .TARGET}}'

  fly:
    dir: ./garden-app
    cmds:
      - flyctl deploy
