version: "3.8"
services:
  influxdb:
    image: "quay.io/influxdb/influxdb:v2.0.2"
    ports:
      - "8086:8086"

  influxdb_setup:
    image: "quay.io/influxdb/influxdb:v2.0.2"
    volumes:
      - "./influxdb_setup:/entrypoint"
    command: "/entrypoint/entrypoint.sh"
    depends_on:
      - influxdb
    env_file:
      - env_file

  telegraf:
    image: "telegraf"
    volumes:
      - "./telegraf:/etc/telegraf"
    env_file:
      - env_file

  mqtt:
    image: "eclipse-mosquitto:2.0"
    volumes:
      - "./mosquitto:/mosquitto/config"
    ports:
      - "1883:1883"
      - "9001:9001"
