log:
  level: info
  format: text
web_server:
  port: 8080
mqtt:
  broker: "mqtt"
  port: 1883
  client_id: "garden-app-acorn"
influxdb:
  address: "http://influxdb:8086"
  token: "my-secret-token"
  org: "garden"
  bucket: "garden"
storage:
  driver: "hashmap"
  options:
    filename: "/app/configs/gardens.yaml"
controller:
  topic_prefix: "garden"
  num_zones: 3
  publish_water_event: true
  publish_health: true
  health_interval: 1m
