apiVersion: apps/v1
kind: Deployment
metadata:
  name: garden-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garden-controller
  template:
    metadata:
      labels:
        app: garden-controller
    spec:
      containers:
        - name: garden-controller
          image: ghcr.io/calvinmclean/garden-app
          volumeMounts:
            - name: config
              mountPath: /config
          args:
            - controller
            - --config=/config/config.yaml
            - --enable-ui=false
            - --log-level=debug
      volumes:
        - name: config
          configMap:
            name: garden-controller-config
