// Code generated by mockery v2.53.0. DO NOT EDIT.

package weather

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

// GetAverageHighTemperature provides a mock function with given fields: ctx, since
func (_m *MockClient) GetAverageHighTemperature(ctx context.Context, since time.Duration) (float32, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for GetAverageHighTemperature")
	}

	var r0 float32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) (float32, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) float32); ok {
		r0 = rf(ctx, since)
	} else {
		r0 = ret.Get(0).(float32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalRain provides a mock function with given fields: ctx, since
func (_m *MockClient) GetTotalRain(ctx context.Context, since time.Duration) (float32, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalRain")
	}

	var r0 float32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) (float32, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) float32); ok {
		r0 = rf(ctx, since)
	} else {
		r0 = ret.Get(0).(float32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
