apiVersion: apps/v1
kind: Deployment
metadata:
  name: garden-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garden-app
  template:
    metadata:
      labels:
        app: garden-app
    spec:
      containers:
        - name: garden-app
          image: calvinmclean/garden-app
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /config
          args:
            - server
            - --config
            - /config/config.yaml
      volumes:
        - name: config
          configMap:
            name: garden-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: garden-app
  namespace: default
spec:
  type: NodePort
  selector:
    app: garden-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: garden-app-config
  namespace: default
data:
  config.yaml: |
    web_server:
      port: 80
    mqtt:
      broker: "mosquitto"
      port: 1883
      client_id: "garden-app"
      watering_topic: "{{.Garden}}/command/water"
      skip_topic: "{{.Garden}}/command/skip"
      stop_topic: "{{.Garden}}/command/stop"
      stop_all_topic: "{{.Garden}}/command/stop_all"
    influxdb:
      address: "http://influxdb:8086"
      token: "my-secret-token"
      org: "garden"
      bucket: "water"
    storage:
      type: "ConfigMap"
      options:
        name: "garden-app-config"
        key: "plants.yaml"
  plants.yaml: |
    bvtomctnf4q280jbci3g:
      name: Basil
      id: bvtomctnf4q280jbci3g
      garden: garden
      plant_position: 1
      start_date: 2021-01-14T22:00:10.880112-07:00
      watering_strategy:
          watering_amount: 8000
          interval: 24h
    9m4e2mr0ui3e8a215n4g:
        name: Cherry Tomato
        id: 9m4e2mr0ui3e8a215n4g
        garden: garden
        plant_position: 2
        start_date: 2021-01-14T22:00:20.880112-07:00
        watering_strategy:
            watering_amount: 10000
            interval: 24h
    bvtol25nf4q25rqmno5g:
        name: Green Onion
        id: bvtol25nf4q25rqmno5g
        garden: garden
        plant_position: 0
        start_date: 2021-01-14T22:00:00.880112-07:00
        watering_strategy:
            watering_amount: 10000
            interval: 24h
    c16h30adveu3dmtmq7mg:
        name: Money Tree
        id: c16h30adveu3dmtmq7mg
        garden: office-plant
        plant_position: 0
        start_date: 2021-03-13T19:24:49.097629252Z
        watering_strategy:
            watering_amount: 10000
            interval: 72h
            minimum_moisture: 45
# in order to read/write the ConfigMap from the pod, you need to create a ClusterRoleBinding:
# kubectl create clusterrolebinding default --clusterrole=admin --serviceaccount=default:default
