apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-environment
  namespace: default
data:
  # General
  ADMIN_USER: admin
  ADMIN_PSWD: adminadmin
  # InfluxDB
  INFLUXDB_TOKEN: my-secret-token
  INFLUXDB_ORG: garden
  INFLUXDB_BUCKET: water
  # Telegraf
  MQTT_WATER_TOPIC: garden/data/water
  MQTT_MOISTURE_TOPIC: garden/data/moisture
  # Grafana
  GF_PATHS_PROVISIONING: /etc/grafana/provisioning
