apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: telegraf
          volumeMounts:
            - name: config
              mountPath: /etc/telegraf
          env:
            - name: MQTT_WATER_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: shared-environment
                  key: MQTT_WATER_TOPIC
            - name: MQTT_LIGHT_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: shared-environment
                  key: MQTT_LIGHT_TOPIC
            - name: MQTT_MOISTURE_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: shared-environment
                  key: MQTT_MOISTURE_TOPIC
            - name: MQTT_LOGGING_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: shared-environment
                  key: MQTT_LOGGING_TOPIC
            - name: MQTT_HEALTH_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: shared-environment
                  key: MQTT_HEALTH_TOPIC
            - name: INFLUXDB_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: shared-environment
                  key: INFLUXDB_TOKEN
            - name: INFLUXDB_ORG
              valueFrom:
                configMapKeyRef:
                  name: shared-environment
                  key: INFLUXDB_ORG
            - name: INFLUXDB_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: shared-environment
                  key: INFLUXDB_BUCKET
      volumes:
        - name: config
          configMap:
            name: telegraf-config
