version: "2"

run:
  timeout: 2m
  issues-exit-code: 1
  tests: true

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - unused
    - staticcheck
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: exported
          disabled: true
    staticcheck:
      checks:
        - all
        - -QF1008 # could remove embedded field from selector

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
