run:
  timeout: 2m
  issues-exit-code: 1
  tests: true
  skip-files:
    - cmd/completion.go

issues:
  exclude:
    - "Error return value of `render.Render` is not checked"
    - "Error return value of `viper.BindPFlag` is not checked"
    - "Error return value of `.+Command.RegisterFlagCompletionFunc` is not checked"
    - "Error return value of `.+.Write` is not checked"
  exclude-rules:
    - path: ".*_test\\.go"
      linters:
        - revive

output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number
  # print lines of code with issue, default is true
  print-issued-lines: true
  # print linter name in the end of issue text, default is true
  print-linter-name: true
  # make issues output unique by line, default is true
  uniq-by-line: true
  # add a prefix to the output file references; default is no prefix
  path-prefix: ""
  # sorts results by: filepath, line and column
  sort-results: true

linters:
  enable:
    - bodyclose
    - errcheck
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unused
