# fly.toml app configuration file generated for garden-app-demo on 2024-05-05T18:49:53-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'garden-app-demo'
primary_region = 'lax'

[build]
build-target = "demo"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
