apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: garden-app
build:
  artifacts:
    - image: ghcr.io/calvinmclean/garden-app
  local: {}
deploy:
  kustomize:
    paths:
      - ../deploy/overlays/dev
