# Profiles:
#   - test: run just the services required for integration testing
#   - run-local: run required services + extras like Grafana and Prometheus
#   - demo: run everything, including an instance of garden-app and garden-controller

version: "3.9"
services:
  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    volumes:
      - "grafana:/var/lib/grafana"
      - "./configs/grafana/datasources:/etc/grafana/provisioning/datasources"
      - "./configs/grafana/dashboards:/etc/grafana/provisioning/dashboards"
    env_file:
      - env_file
    profiles:
      - run-local
      - demo

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./configs/prometheus:/etc/prometheus"
    profiles:
      - run-local
      - demo

  influxdb:
    image: "influxdb:latest"
    ports:
      - "8086:8086"
    volumes:
      - "influxdb:/var/lib/influxdb2"
    profiles:
      - test
      - run-local
      - demo

  influxdb_setup:
    image: "influxdb:latest"
    volumes:
      - "./influxdb_setup:/entrypoint"
    command: "/entrypoint/entrypoint.sh"
    depends_on:
      - influxdb
    env_file:
      - env_file
    profiles:
      - test
      - run-local
      - demo

  telegraf:
    image: "telegraf"
    volumes:
      - "./configs/telegraf:/etc/telegraf"
    env_file:
      - env_file
    profiles:
      - test
      - run-local
      - demo

  mqtt:
    image: "eclipse-mosquitto:2.0"
    volumes:
      - "./configs/mosquitto:/mosquitto/config"
    ports:
      - "1883:1883"
      - "9001:9001"
    profiles:
      - test
      - run-local
      - demo

  garden-app:
    image: "ghcr.io/calvinmclean/garden-app:latest"
    ports:
      - "8080:8080"
    volumes:
      - "./configs/garden-app:/app/configs"
    command:
      - "server"
      - "--config=/app/configs/config.yaml"
    profiles:
      - demo

  garden-controller:
    image: "ghcr.io/calvinmclean/garden-app:latest"
    volumes:
      - "./configs/garden-app:/app/configs"
    command:
      - "controller"
      - "--config=/app/configs/config.yaml"
      - "--enable-ui=false"
    profiles:
      - demo

volumes:
  influxdb:
  grafana:
