// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: controller_info_queries.sql

package db

import (
	"context"
	"database/sql"
)

const deleteControllerInfo = `-- name: DeleteControllerInfo :exec
DELETE FROM garden_controller_info WHERE garden_id = ?
`

func (q *Queries) DeleteControllerInfo(ctx context.Context, gardenID string) error {
	_, err := q.db.ExecContext(ctx, deleteControllerInfo, gardenID)
	return err
}

const getControllerInfo = `-- name: GetControllerInfo :one
SELECT garden_id, mac_address, ip_address, firmware_version, updated_at FROM garden_controller_info WHERE garden_id = ? LIMIT 1
`

func (q *Queries) GetControllerInfo(ctx context.Context, gardenID string) (GardenControllerInfo, error) {
	row := q.db.QueryRowContext(ctx, getControllerInfo, gardenID)
	var i GardenControllerInfo
	err := row.Scan(
		&i.GardenID,
		&i.MacAddress,
		&i.IpAddress,
		&i.FirmwareVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertControllerInfo = `-- name: UpsertControllerInfo :exec
INSERT INTO garden_controller_info (garden_id, mac_address, ip_address, firmware_version, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (garden_id)
DO UPDATE SET
    mac_address = EXCLUDED.mac_address,
    ip_address = EXCLUDED.ip_address,
    firmware_version = EXCLUDED.firmware_version,
    updated_at = EXCLUDED.updated_at
`

type UpsertControllerInfoParams struct {
	GardenID        string
	MacAddress      sql.NullString
	IpAddress       sql.NullString
	FirmwareVersion sql.NullString
	UpdatedAt       string
}

func (q *Queries) UpsertControllerInfo(ctx context.Context, arg UpsertControllerInfoParams) error {
	_, err := q.db.ExecContext(ctx, upsertControllerInfo,
		arg.GardenID,
		arg.MacAddress,
		arg.IpAddress,
		arg.FirmwareVersion,
		arg.UpdatedAt,
	)
	return err
}
