// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: garden_queries.sql

package db

import (
	"context"
	"database/sql"
)

const deleteGarden = `-- name: DeleteGarden :exec
DELETE FROM gardens WHERE id = ?
`

func (q *Queries) DeleteGarden(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGarden, id)
	return err
}

const getGarden = `-- name: GetGarden :one
SELECT g.id, g.name, g.topic_prefix, g.max_zones, g.created_at, g.end_date, g.notification_client_id, g.notification_settings, g.controller_config, g.light_schedule, g.fan_schedule, ci.mac_address, ci.ip_address, ci.firmware_version, ci.updated_at
FROM gardens g
LEFT JOIN garden_controller_info ci ON g.id = ci.garden_id
WHERE g.id = ? LIMIT 1
`

type GetGardenRow struct {
	ID                   string
	Name                 string
	TopicPrefix          string
	MaxZones             int64
	CreatedAt            string
	EndDate              sql.NullString
	NotificationClientID sql.NullString
	NotificationSettings sql.NullString
	ControllerConfig     sql.NullString
	LightSchedule        sql.NullString
	FanSchedule          sql.NullString
	MacAddress           sql.NullString
	IpAddress            sql.NullString
	FirmwareVersion      sql.NullString
	UpdatedAt            sql.NullString
}

func (q *Queries) GetGarden(ctx context.Context, id string) (GetGardenRow, error) {
	row := q.db.QueryRowContext(ctx, getGarden, id)
	var i GetGardenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TopicPrefix,
		&i.MaxZones,
		&i.CreatedAt,
		&i.EndDate,
		&i.NotificationClientID,
		&i.NotificationSettings,
		&i.ControllerConfig,
		&i.LightSchedule,
		&i.FanSchedule,
		&i.MacAddress,
		&i.IpAddress,
		&i.FirmwareVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const getGardenByTopicPrefix = `-- name: GetGardenByTopicPrefix :one
SELECT g.id, g.name, g.topic_prefix, g.max_zones, g.created_at, g.end_date, g.notification_client_id, g.notification_settings, g.controller_config, g.light_schedule, g.fan_schedule, ci.mac_address, ci.ip_address, ci.firmware_version, ci.updated_at
FROM gardens g
LEFT JOIN garden_controller_info ci ON g.id = ci.garden_id
WHERE g.topic_prefix = ? LIMIT 1
`

type GetGardenByTopicPrefixRow struct {
	ID                   string
	Name                 string
	TopicPrefix          string
	MaxZones             int64
	CreatedAt            string
	EndDate              sql.NullString
	NotificationClientID sql.NullString
	NotificationSettings sql.NullString
	ControllerConfig     sql.NullString
	LightSchedule        sql.NullString
	FanSchedule          sql.NullString
	MacAddress           sql.NullString
	IpAddress            sql.NullString
	FirmwareVersion      sql.NullString
	UpdatedAt            sql.NullString
}

func (q *Queries) GetGardenByTopicPrefix(ctx context.Context, topicPrefix string) (GetGardenByTopicPrefixRow, error) {
	row := q.db.QueryRowContext(ctx, getGardenByTopicPrefix, topicPrefix)
	var i GetGardenByTopicPrefixRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TopicPrefix,
		&i.MaxZones,
		&i.CreatedAt,
		&i.EndDate,
		&i.NotificationClientID,
		&i.NotificationSettings,
		&i.ControllerConfig,
		&i.LightSchedule,
		&i.FanSchedule,
		&i.MacAddress,
		&i.IpAddress,
		&i.FirmwareVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveGardens = `-- name: ListActiveGardens :many
SELECT g.id, g.name, g.topic_prefix, g.max_zones, g.created_at, g.end_date, g.notification_client_id, g.notification_settings, g.controller_config, g.light_schedule, g.fan_schedule, ci.mac_address, ci.ip_address, ci.firmware_version, ci.updated_at
FROM gardens g
LEFT JOIN garden_controller_info ci ON g.id = ci.garden_id
WHERE g.end_date IS NULL
   OR g.end_date > ?
`

type ListActiveGardensRow struct {
	ID                   string
	Name                 string
	TopicPrefix          string
	MaxZones             int64
	CreatedAt            string
	EndDate              sql.NullString
	NotificationClientID sql.NullString
	NotificationSettings sql.NullString
	ControllerConfig     sql.NullString
	LightSchedule        sql.NullString
	FanSchedule          sql.NullString
	MacAddress           sql.NullString
	IpAddress            sql.NullString
	FirmwareVersion      sql.NullString
	UpdatedAt            sql.NullString
}

func (q *Queries) ListActiveGardens(ctx context.Context, endDate sql.NullString) ([]ListActiveGardensRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveGardens, endDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveGardensRow
	for rows.Next() {
		var i ListActiveGardensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TopicPrefix,
			&i.MaxZones,
			&i.CreatedAt,
			&i.EndDate,
			&i.NotificationClientID,
			&i.NotificationSettings,
			&i.ControllerConfig,
			&i.LightSchedule,
			&i.FanSchedule,
			&i.MacAddress,
			&i.IpAddress,
			&i.FirmwareVersion,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllGardens = `-- name: ListAllGardens :many
SELECT g.id, g.name, g.topic_prefix, g.max_zones, g.created_at, g.end_date, g.notification_client_id, g.notification_settings, g.controller_config, g.light_schedule, g.fan_schedule, ci.mac_address, ci.ip_address, ci.firmware_version, ci.updated_at
FROM gardens g
LEFT JOIN garden_controller_info ci ON g.id = ci.garden_id
`

type ListAllGardensRow struct {
	ID                   string
	Name                 string
	TopicPrefix          string
	MaxZones             int64
	CreatedAt            string
	EndDate              sql.NullString
	NotificationClientID sql.NullString
	NotificationSettings sql.NullString
	ControllerConfig     sql.NullString
	LightSchedule        sql.NullString
	FanSchedule          sql.NullString
	MacAddress           sql.NullString
	IpAddress            sql.NullString
	FirmwareVersion      sql.NullString
	UpdatedAt            sql.NullString
}

func (q *Queries) ListAllGardens(ctx context.Context) ([]ListAllGardensRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllGardens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllGardensRow
	for rows.Next() {
		var i ListAllGardensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TopicPrefix,
			&i.MaxZones,
			&i.CreatedAt,
			&i.EndDate,
			&i.NotificationClientID,
			&i.NotificationSettings,
			&i.ControllerConfig,
			&i.LightSchedule,
			&i.FanSchedule,
			&i.MacAddress,
			&i.IpAddress,
			&i.FirmwareVersion,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGardenEndDate = `-- name: SetGardenEndDate :exec
UPDATE gardens
SET end_date = ?
WHERE id = ?
`

type SetGardenEndDateParams struct {
	EndDate sql.NullString
	ID      string
}

func (q *Queries) SetGardenEndDate(ctx context.Context, arg SetGardenEndDateParams) error {
	_, err := q.db.ExecContext(ctx, setGardenEndDate, arg.EndDate, arg.ID)
	return err
}

const upsertGarden = `-- name: UpsertGarden :exec
INSERT INTO gardens (
  id, name, topic_prefix,
  max_zones,
  created_at, end_date,
  notification_client_id, notification_settings,
  controller_config, light_schedule, fan_schedule
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) ON CONFLICT (id)
DO UPDATE SET
  name = EXCLUDED.name,
  topic_prefix = EXCLUDED.topic_prefix,
  max_zones = EXCLUDED.max_zones,
  end_date = EXCLUDED.end_date,
  notification_client_id = EXCLUDED.notification_client_id,
  notification_settings = EXCLUDED.notification_settings,
  controller_config = EXCLUDED.controller_config,
  light_schedule = EXCLUDED.light_schedule,
  fan_schedule = EXCLUDED.fan_schedule
`

type UpsertGardenParams struct {
	ID                   string
	Name                 string
	TopicPrefix          string
	MaxZones             int64
	CreatedAt            string
	EndDate              sql.NullString
	NotificationClientID sql.NullString
	NotificationSettings sql.NullString
	ControllerConfig     sql.NullString
	LightSchedule        sql.NullString
	FanSchedule          sql.NullString
}

func (q *Queries) UpsertGarden(ctx context.Context, arg UpsertGardenParams) error {
	_, err := q.db.ExecContext(ctx, upsertGarden,
		arg.ID,
		arg.Name,
		arg.TopicPrefix,
		arg.MaxZones,
		arg.CreatedAt,
		arg.EndDate,
		arg.NotificationClientID,
		arg.NotificationSettings,
		arg.ControllerConfig,
		arg.LightSchedule,
		arg.FanSchedule,
	)
	return err
}
