// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
)

type Garden struct {
	ID                   string
	Name                 string
	TopicPrefix          string
	MaxZones             int64
	TempHumidSensor      bool
	CreatedAt            string
	EndDate              sql.NullString
	NotificationClientID sql.NullString
	NotificationSettings sql.NullString
	ControllerConfig     sql.NullString
	LightSchedule        sql.NullString
}

type NotificationClient struct {
	ID   string
	Name string
	Url  string
}

type UserSetting struct {
	Key   string
	Value string
}

type WaterRoutine struct {
	ID    string
	Name  string
	Steps json.RawMessage
}

type WaterSchedule struct {
	ID                     string
	Name                   sql.NullString
	Description            sql.NullString
	Duration               int64
	Interval               int64
	StartDate              string
	StartTime              string
	EndDate                sql.NullString
	ActivePeriodStartMonth sql.NullString
	ActivePeriodEndMonth   sql.NullString
	WeatherControl         sql.NullString
	NotificationClientID   sql.NullString
}

type WeatherClient struct {
	ID      string
	Type    string
	Options json.RawMessage
	Name    string
}

type Zone struct {
	ID                 string
	Name               string
	GardenID           string
	DetailsDescription sql.NullString
	DetailsNotes       sql.NullString
	Position           sql.NullInt64
	SkipCount          sql.NullInt64
	CreatedAt          string
	EndDate            sql.NullString
	WaterScheduleIds   sql.NullString
}
