// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: note_queries.sql

package db

import (
	"context"
	"database/sql"
)

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes WHERE id = ?
`

func (q *Queries) DeleteNote(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const getNote = `-- name: GetNote :one
SELECT id, title, content, created_at, garden_id, zone_id FROM notes
WHERE id = ? LIMIT 1
`

func (q *Queries) GetNote(ctx context.Context, id string) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.GardenID,
		&i.ZoneID,
	)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT id, title, content, created_at, garden_id, zone_id FROM notes
`

func (q *Queries) ListNotes(ctx context.Context) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.GardenID,
			&i.ZoneID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNote = `-- name: UpsertNote :exec
INSERT INTO notes (
  id, title, content,
  created_at,
  garden_id, zone_id
) VALUES (
  ?, ?, ?, ?, ?, ?
) ON CONFLICT (id)
DO UPDATE SET
  title = EXCLUDED.title,
  content = EXCLUDED.content,
  garden_id = EXCLUDED.garden_id,
  zone_id = EXCLUDED.zone_id
`

type UpsertNoteParams struct {
	ID        string
	Title     string
	Content   sql.NullString
	CreatedAt string
	GardenID  sql.NullString
	ZoneID    sql.NullString
}

func (q *Queries) UpsertNote(ctx context.Context, arg UpsertNoteParams) error {
	_, err := q.db.ExecContext(ctx, upsertNote,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.CreatedAt,
		arg.GardenID,
		arg.ZoneID,
	)
	return err
}
