// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_client_queries.sql

package db

import (
	"context"
)

const deleteNotificationClient = `-- name: DeleteNotificationClient :exec
DELETE FROM notification_clients WHERE id = ?
`

func (q *Queries) DeleteNotificationClient(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationClient, id)
	return err
}

const getNotificationClient = `-- name: GetNotificationClient :one
SELECT id, name, url FROM notification_clients
WHERE id = ? LIMIT 1
`

func (q *Queries) GetNotificationClient(ctx context.Context, id string) (NotificationClient, error) {
	row := q.db.QueryRowContext(ctx, getNotificationClient, id)
	var i NotificationClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.URL,
	)
	return i, err
}

const listNotificationClients = `-- name: ListNotificationClients :many
SELECT id, name, url FROM notification_clients
`

func (q *Queries) ListNotificationClients(ctx context.Context) ([]NotificationClient, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationClient
	for rows.Next() {
		var i NotificationClient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.URL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNotificationClient = `-- name: UpsertNotificationClient :exec
INSERT INTO notification_clients (
  id, name, url
) VALUES (
  ?, ?, ?
) ON CONFLICT (id)
DO UPDATE SET
  name = EXCLUDED.name,
  url = EXCLUDED.url
`

type UpsertNotificationClientParams struct {
	ID   string
	Name string
	URL  string
}

func (q *Queries) UpsertNotificationClient(ctx context.Context, arg UpsertNotificationClientParams) error {
	_, err := q.db.ExecContext(ctx, upsertNotificationClient,
		arg.ID,
		arg.Name,
		arg.URL,
	)
	return err
}
