// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_settings_queries.sql

package db

import (
	"context"
)

const deleteUserSetting = `-- name: DeleteUserSetting :exec
DELETE FROM user_settings WHERE key = ?
`

func (q *Queries) DeleteUserSetting(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSetting, key)
	return err
}

const getUserSetting = `-- name: GetUserSetting :one
SELECT "key", value FROM user_settings WHERE key = ? LIMIT 1
`

func (q *Queries) GetUserSetting(ctx context.Context, key string) (UserSetting, error) {
	row := q.db.QueryRowContext(ctx, getUserSetting, key)
	var i UserSetting
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}

const upsertUserSetting = `-- name: UpsertUserSetting :exec
INSERT INTO user_settings (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type UpsertUserSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) UpsertUserSetting(ctx context.Context, arg UpsertUserSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserSetting, arg.Key, arg.Value)
	return err
}
