// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: water_routine_queries.sql

package db

import (
	"context"
	"encoding/json"
)

const deleteWaterRoutine = `-- name: DeleteWaterRoutine :exec
DELETE FROM water_routines WHERE id = ?
`

func (q *Queries) DeleteWaterRoutine(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWaterRoutine, id)
	return err
}

const getWaterRoutine = `-- name: GetWaterRoutine :one
SELECT id, name, steps FROM water_routines
WHERE id = ? LIMIT 1
`

func (q *Queries) GetWaterRoutine(ctx context.Context, id string) (WaterRoutine, error) {
	row := q.db.QueryRowContext(ctx, getWaterRoutine, id)
	var i WaterRoutine
	err := row.Scan(&i.ID, &i.Name, &i.Steps)
	return i, err
}

const listWaterRoutines = `-- name: ListWaterRoutines :many
SELECT id, name, steps FROM water_routines
`

func (q *Queries) ListWaterRoutines(ctx context.Context) ([]WaterRoutine, error) {
	rows, err := q.db.QueryContext(ctx, listWaterRoutines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaterRoutine
	for rows.Next() {
		var i WaterRoutine
		if err := rows.Scan(&i.ID, &i.Name, &i.Steps); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWaterRoutine = `-- name: UpsertWaterRoutine :exec
INSERT INTO water_routines (
  id, name, steps
) VALUES (
  ?, ?, ?
) ON CONFLICT (id)
DO UPDATE SET
  name = EXCLUDED.name,
  steps = EXCLUDED.steps
`

type UpsertWaterRoutineParams struct {
	ID    string
	Name  string
	Steps json.RawMessage
}

func (q *Queries) UpsertWaterRoutine(ctx context.Context, arg UpsertWaterRoutineParams) error {
	_, err := q.db.ExecContext(ctx, upsertWaterRoutine, arg.ID, arg.Name, arg.Steps)
	return err
}
