name: CI

on:
  push:
    branches-ignore: ["assets"]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  PROJECT_NAME: garden-app

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check for debug prints
        id: check-print
        working-directory: ./${{ env.PROJECT_NAME }}
        run: if [[ -n $(grep -R "fmt.Print" | grep -v vendor) ]]; then echo "Did you forget to remove debug prints?" && false; else echo "All good!"; fi

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install golint
        run: go get -u golang.org/x/lint/golint

      - name: Lint
        id: lint
        working-directory: ./${{ env.PROJECT_NAME }}
        run: echo "::set-output name=LINT_OUTPUT::$(golint $(go list ./... | grep -v /vendor/))"

      - name: Lint Check
        run: test -z "${{ steps.lint.outputs.LINT_OUTPUT }}"

      - name: Format
        id: format
        working-directory: ./${{ env.PROJECT_NAME }}
        run: echo "::set-output name=FORMAT_OUTPUT::$(gofmt -d -s $(find . -name "*.go" | grep -v /vendor/))"

      - name: Format Check
        run: test -z "${{ steps.format.outputs.FORMAT_OUTPUT }}"

      - name: Vet
        id: vet
        working-directory: ./${{ env.PROJECT_NAME }}
        run: echo "::set-output name=VET_OUTPUT::$(go vet $(go list ./... | grep -v /vendor/))"

      - name: Vet Check
        run: test -z "${{ steps.vet.outputs.VET_OUTPUT }}"

      - name: Test
        working-directory: ./${{ env.PROJECT_NAME }}
        run: go test ./...

  build:
    needs: go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.PROJECT_NAME }}
          flavor: |
            latest=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ env.PROJECT_NAME }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
