// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: garden_queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const deleteGarden = `-- name: DeleteGarden :exec
DELETE FROM gardens WHERE id = ?
`

func (q *Queries) DeleteGarden(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGarden, id)
	return err
}

const getGarden = `-- name: GetGarden :one
SELECT id, name, topic_prefix, max_zones, temp_humid_sensor, created_at, end_date, notification_client_id, notification_settings, controller_config, light_schedule FROM gardens
WHERE id = ? LIMIT 1
`

func (q *Queries) GetGarden(ctx context.Context, id string) (Garden, error) {
	row := q.db.QueryRowContext(ctx, getGarden, id)
	var i Garden
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TopicPrefix,
		&i.MaxZones,
		&i.TempHumidSensor,
		&i.CreatedAt,
		&i.EndDate,
		&i.NotificationClientID,
		&i.NotificationSettings,
		&i.ControllerConfig,
		&i.LightSchedule,
	)
	return i, err
}

const listActiveGardens = `-- name: ListActiveGardens :many
SELECT id, name, topic_prefix, max_zones, temp_humid_sensor, created_at, end_date, notification_client_id, notification_settings, controller_config, light_schedule FROM gardens WHERE end_date IS NULL
   OR end_date > ?
`

func (q *Queries) ListActiveGardens(ctx context.Context, endDate sql.NullTime) ([]Garden, error) {
	rows, err := q.db.QueryContext(ctx, listActiveGardens, endDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Garden
	for rows.Next() {
		var i Garden
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TopicPrefix,
			&i.MaxZones,
			&i.TempHumidSensor,
			&i.CreatedAt,
			&i.EndDate,
			&i.NotificationClientID,
			&i.NotificationSettings,
			&i.ControllerConfig,
			&i.LightSchedule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllGardens = `-- name: ListAllGardens :many
SELECT id, name, topic_prefix, max_zones, temp_humid_sensor, created_at, end_date, notification_client_id, notification_settings, controller_config, light_schedule FROM gardens
`

func (q *Queries) ListAllGardens(ctx context.Context) ([]Garden, error) {
	rows, err := q.db.QueryContext(ctx, listAllGardens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Garden
	for rows.Next() {
		var i Garden
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TopicPrefix,
			&i.MaxZones,
			&i.TempHumidSensor,
			&i.CreatedAt,
			&i.EndDate,
			&i.NotificationClientID,
			&i.NotificationSettings,
			&i.ControllerConfig,
			&i.LightSchedule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGardenEndDate = `-- name: SetGardenEndDate :exec
UPDATE gardens
SET end_date = ?
WHERE id = ?
`

type SetGardenEndDateParams struct {
	EndDate sql.NullTime
	ID      string
}

func (q *Queries) SetGardenEndDate(ctx context.Context, arg SetGardenEndDateParams) error {
	_, err := q.db.ExecContext(ctx, setGardenEndDate, arg.EndDate, arg.ID)
	return err
}

const upsertGarden = `-- name: UpsertGarden :exec
INSERT INTO gardens (
  id, name, topic_prefix,
  max_zones, temp_humid_sensor,
  created_at, end_date,
  notification_client_id, notification_settings,
  controller_config, light_schedule
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) ON CONFLICT (id)
DO UPDATE SET
  name = EXCLUDED.name,
  topic_prefix = EXCLUDED.topic_prefix,
  max_zones = EXCLUDED.max_zones,
  temp_humid_sensor = EXCLUDED.temp_humid_sensor,
  end_date = EXCLUDED.end_date,
  notification_client_id = EXCLUDED.notification_client_id,
  notification_settings = EXCLUDED.notification_settings,
  controller_config = EXCLUDED.controller_config,
  light_schedule = EXCLUDED.light_schedule
`

type UpsertGardenParams struct {
	ID                   string
	Name                 string
	TopicPrefix          string
	MaxZones             int64
	TempHumidSensor      bool
	CreatedAt            time.Time
	EndDate              sql.NullTime
	NotificationClientID sql.NullString
	NotificationSettings sql.NullString
	ControllerConfig     sql.NullString
	LightSchedule        sql.NullString
}

func (q *Queries) UpsertGarden(ctx context.Context, arg UpsertGardenParams) error {
	_, err := q.db.ExecContext(ctx, upsertGarden,
		arg.ID,
		arg.Name,
		arg.TopicPrefix,
		arg.MaxZones,
		arg.TempHumidSensor,
		arg.CreatedAt,
		arg.EndDate,
		arg.NotificationClientID,
		arg.NotificationSettings,
		arg.ControllerConfig,
		arg.LightSchedule,
	)
	return err
}
