// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Garden struct {
	ID                   string
	Name                 string
	TopicPrefix          string
	MaxZones             interface{}
	TempHumidSensor      bool
	CreatedAt            time.Time
	EndDate              sql.NullTime
	NotificationClientID sql.NullString
	NotificationSettings json.RawMessage
	ControllerConfig     json.RawMessage
	LightSchedule        json.RawMessage
}

type NotificationClient struct {
	ID      string
	Name    string
	Type    string
	Options json.RawMessage
}

type WaterRoutine struct {
	ID    string
	Name  string
	Steps json.RawMessage
}

type WaterSchedule struct {
	ID                     string
	Name                   sql.NullString
	Description            sql.NullString
	Duration               interface{}
	Interval               interface{}
	StartDate              time.Time
	StartTime              string
	EndDate                sql.NullTime
	ActivePeriodStartMonth sql.NullString
	ActivePeriodEndMonth   sql.NullString
	WeatherControl         json.RawMessage
	NotificationClientID   sql.NullString
}

type WeatherClient struct {
	ID      string
	Type    string
	Options json.RawMessage
}

type Zone struct {
	ID                 string
	Name               string
	GardenID           string
	DetailsDescription string
	DetailsNotes       string
	Position           interface{}
	SkipCount          interface{}
	CreatedAt          time.Time
	EndDate            sql.NullTime
	WaterScheduleIds   sql.NullString
}
