// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: water_schedule_queries.sql

package db

import (
	"context"
	"database/sql"
)

const deleteWaterSchedule = `-- name: DeleteWaterSchedule :exec
DELETE FROM water_schedules WHERE id = ?
`

func (q *Queries) DeleteWaterSchedule(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWaterSchedule, id)
	return err
}

const findWaterSchedulesByWeatherClientID = `-- name: FindWaterSchedulesByWeatherClientID :many
SELECT id, name, description, duration, interval, start_date, start_time, end_date, active_period_start_month, active_period_end_month, weather_control, notification_client_id FROM water_schedules
WHERE weather_control IS NOT NULL AND (
    json_extract(weather_control, '$.rain_control.client_id') = ?
    OR json_extract(weather_control, '$.temperature_control.client_id') = ?
)
`

type FindWaterSchedulesByWeatherClientIDParams struct {
	WeatherControl   sql.NullString
	WeatherControl_2 sql.NullString
}

func (q *Queries) FindWaterSchedulesByWeatherClientID(ctx context.Context, arg FindWaterSchedulesByWeatherClientIDParams) ([]WaterSchedule, error) {
	rows, err := q.db.QueryContext(ctx, findWaterSchedulesByWeatherClientID, arg.WeatherControl, arg.WeatherControl_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaterSchedule
	for rows.Next() {
		var i WaterSchedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Duration,
			&i.Interval,
			&i.StartDate,
			&i.StartTime,
			&i.EndDate,
			&i.ActivePeriodStartMonth,
			&i.ActivePeriodEndMonth,
			&i.WeatherControl,
			&i.NotificationClientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWaterSchedule = `-- name: GetWaterSchedule :one
SELECT id, name, description, duration, interval, start_date, start_time, end_date, active_period_start_month, active_period_end_month, weather_control, notification_client_id FROM water_schedules
WHERE id = ? LIMIT 1
`

func (q *Queries) GetWaterSchedule(ctx context.Context, id string) (WaterSchedule, error) {
	row := q.db.QueryRowContext(ctx, getWaterSchedule, id)
	var i WaterSchedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Duration,
		&i.Interval,
		&i.StartDate,
		&i.StartTime,
		&i.EndDate,
		&i.ActivePeriodStartMonth,
		&i.ActivePeriodEndMonth,
		&i.WeatherControl,
		&i.NotificationClientID,
	)
	return i, err
}

const listActiveWaterSchedules = `-- name: ListActiveWaterSchedules :many
SELECT id, name, description, duration, interval, start_date, start_time, end_date, active_period_start_month, active_period_end_month, weather_control, notification_client_id FROM water_schedules WHERE end_date IS NULL
   OR end_date > ?
`

func (q *Queries) ListActiveWaterSchedules(ctx context.Context, endDate sql.NullString) ([]WaterSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listActiveWaterSchedules, endDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaterSchedule
	for rows.Next() {
		var i WaterSchedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Duration,
			&i.Interval,
			&i.StartDate,
			&i.StartTime,
			&i.EndDate,
			&i.ActivePeriodStartMonth,
			&i.ActivePeriodEndMonth,
			&i.WeatherControl,
			&i.NotificationClientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllWaterSchedules = `-- name: ListAllWaterSchedules :many
SELECT id, name, description, duration, interval, start_date, start_time, end_date, active_period_start_month, active_period_end_month, weather_control, notification_client_id FROM water_schedules
`

func (q *Queries) ListAllWaterSchedules(ctx context.Context) ([]WaterSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listAllWaterSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaterSchedule
	for rows.Next() {
		var i WaterSchedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Duration,
			&i.Interval,
			&i.StartDate,
			&i.StartTime,
			&i.EndDate,
			&i.ActivePeriodStartMonth,
			&i.ActivePeriodEndMonth,
			&i.WeatherControl,
			&i.NotificationClientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWaterScheduleEndDate = `-- name: SetWaterScheduleEndDate :exec
UPDATE water_schedules
SET end_date = ?
WHERE id = ?
`

type SetWaterScheduleEndDateParams struct {
	EndDate sql.NullString
	ID      string
}

func (q *Queries) SetWaterScheduleEndDate(ctx context.Context, arg SetWaterScheduleEndDateParams) error {
	_, err := q.db.ExecContext(ctx, setWaterScheduleEndDate, arg.EndDate, arg.ID)
	return err
}

const upsertWaterSchedule = `-- name: UpsertWaterSchedule :exec
INSERT INTO water_schedules (
  id, name, description,
  duration, interval,
  start_date, start_time,
  end_date,
  active_period_start_month, active_period_end_month,
  weather_control,
  notification_client_id
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) ON CONFLICT (id)
DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  duration = EXCLUDED.duration,
  interval = EXCLUDED.interval,
  start_date = EXCLUDED.start_date,
  start_time = EXCLUDED.start_time,
  end_date = EXCLUDED.end_date,
  active_period_start_month = EXCLUDED.active_period_start_month,
  active_period_end_month = EXCLUDED.active_period_end_month,
  weather_control = EXCLUDED.weather_control,
  notification_client_id = EXCLUDED.notification_client_id
`

type UpsertWaterScheduleParams struct {
	ID                     string
	Name                   sql.NullString
	Description            sql.NullString
	Duration               int64
	Interval               int64
	StartDate              string
	StartTime              string
	EndDate                sql.NullString
	ActivePeriodStartMonth sql.NullString
	ActivePeriodEndMonth   sql.NullString
	WeatherControl         sql.NullString
	NotificationClientID   sql.NullString
}

func (q *Queries) UpsertWaterSchedule(ctx context.Context, arg UpsertWaterScheduleParams) error {
	_, err := q.db.ExecContext(ctx, upsertWaterSchedule,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Duration,
		arg.Interval,
		arg.StartDate,
		arg.StartTime,
		arg.EndDate,
		arg.ActivePeriodStartMonth,
		arg.ActivePeriodEndMonth,
		arg.WeatherControl,
		arg.NotificationClientID,
	)
	return err
}
