// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weather_client_queries.sql

package db

import (
	"context"
	"encoding/json"
)

const deleteWeatherClient = `-- name: DeleteWeatherClient :exec
DELETE FROM weather_clients WHERE id = ?
`

func (q *Queries) DeleteWeatherClient(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWeatherClient, id)
	return err
}

const getWeatherClient = `-- name: GetWeatherClient :one
SELECT id, type, options FROM weather_clients
WHERE id = ? LIMIT 1
`

func (q *Queries) GetWeatherClient(ctx context.Context, id string) (WeatherClient, error) {
	row := q.db.QueryRowContext(ctx, getWeatherClient, id)
	var i WeatherClient
	err := row.Scan(&i.ID, &i.Type, &i.Options)
	return i, err
}

const listWeatherClients = `-- name: ListWeatherClients :many
SELECT id, type, options FROM weather_clients
`

func (q *Queries) ListWeatherClients(ctx context.Context) ([]WeatherClient, error) {
	rows, err := q.db.QueryContext(ctx, listWeatherClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeatherClient
	for rows.Next() {
		var i WeatherClient
		if err := rows.Scan(&i.ID, &i.Type, &i.Options); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWeatherClient = `-- name: UpsertWeatherClient :exec
INSERT INTO weather_clients (
  id, type, options
) VALUES (
  ?, ?, ?
) ON CONFLICT (id)
DO UPDATE SET
  type = EXCLUDED.type,
  options = EXCLUDED.options
`

type UpsertWeatherClientParams struct {
	ID      string
	Type    string
	Options json.RawMessage
}

func (q *Queries) UpsertWeatherClient(ctx context.Context, arg UpsertWeatherClientParams) error {
	_, err := q.db.ExecContext(ctx, upsertWeatherClient, arg.ID, arg.Type, arg.Options)
	return err
}
