// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: zone_queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const deleteZone = `-- name: DeleteZone :exec
DELETE FROM zones WHERE id = ?
`

func (q *Queries) DeleteZone(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteZone, id)
	return err
}

const findZonesByWaterScheduleID = `-- name: FindZonesByWaterScheduleID :many
SELECT id, name, garden_id, details_description, details_notes, position, skip_count, created_at, end_date, water_schedule_ids
FROM zones
WHERE CONCAT(',', water_schedule_ids, ',') LIKE CONCAT('%,', ?, ',%')
`

func (q *Queries) FindZonesByWaterScheduleID(ctx context.Context, concat interface{}) ([]Zone, error) {
	rows, err := q.db.QueryContext(ctx, findZonesByWaterScheduleID, concat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Zone
	for rows.Next() {
		var i Zone
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GardenID,
			&i.DetailsDescription,
			&i.DetailsNotes,
			&i.Position,
			&i.SkipCount,
			&i.CreatedAt,
			&i.EndDate,
			&i.WaterScheduleIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getZone = `-- name: GetZone :one
SELECT id, name, garden_id, details_description, details_notes, position, skip_count, created_at, end_date, water_schedule_ids FROM zones
WHERE id = ? LIMIT 1
`

func (q *Queries) GetZone(ctx context.Context, id string) (Zone, error) {
	row := q.db.QueryRowContext(ctx, getZone, id)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GardenID,
		&i.DetailsDescription,
		&i.DetailsNotes,
		&i.Position,
		&i.SkipCount,
		&i.CreatedAt,
		&i.EndDate,
		&i.WaterScheduleIds,
	)
	return i, err
}

const listZones = `-- name: ListZones :many
SELECT id, name, garden_id, details_description, details_notes, position, skip_count, created_at, end_date, water_schedule_ids FROM zones WHERE garden_id = ?
`

func (q *Queries) ListZones(ctx context.Context, gardenID string) ([]Zone, error) {
	rows, err := q.db.QueryContext(ctx, listZones, gardenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Zone
	for rows.Next() {
		var i Zone
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GardenID,
			&i.DetailsDescription,
			&i.DetailsNotes,
			&i.Position,
			&i.SkipCount,
			&i.CreatedAt,
			&i.EndDate,
			&i.WaterScheduleIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setZoneEndDate = `-- name: SetZoneEndDate :exec
UPDATE zones
SET end_date = ?
WHERE id = ?
`

type SetZoneEndDateParams struct {
	EndDate sql.NullTime
	ID      string
}

func (q *Queries) SetZoneEndDate(ctx context.Context, arg SetZoneEndDateParams) error {
	_, err := q.db.ExecContext(ctx, setZoneEndDate, arg.EndDate, arg.ID)
	return err
}

const upsertZone = `-- name: UpsertZone :exec
INSERT INTO zones (
  id, name, garden_id,
  details_description, details_notes,
  position, skip_count,
  created_at, end_date,
  water_schedule_ids
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) ON CONFLICT (id)
DO UPDATE SET
  name = EXCLUDED.name,
  details_description = EXCLUDED.details_description,
  details_notes = EXCLUDED.details_notes,
  position = EXCLUDED.position,
  skip_count = EXCLUDED.skip_count,
  end_date = EXCLUDED.end_date,
  water_schedule_ids = EXCLUDED.water_schedule_ids
`

type UpsertZoneParams struct {
	ID                 string
	Name               string
	GardenID           string
	DetailsDescription string
	DetailsNotes       string
	Position           interface{}
	SkipCount          interface{}
	CreatedAt          time.Time
	EndDate            sql.NullTime
	WaterScheduleIds   sql.NullString
}

func (q *Queries) UpsertZone(ctx context.Context, arg UpsertZoneParams) error {
	_, err := q.db.ExecContext(ctx, upsertZone,
		arg.ID,
		arg.Name,
		arg.GardenID,
		arg.DetailsDescription,
		arg.DetailsNotes,
		arg.Position,
		arg.SkipCount,
		arg.CreatedAt,
		arg.EndDate,
		arg.WaterScheduleIds,
	)
	return err
}
